Add .pylintrc and run pylint checks in CI workflow.
PiperOrigin-RevId: 364293432

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,18 +24,26 @@ jobs:
       - name: Install dependencies
         run: |
           set -xe
-          python -m pip install --upgrade pip setuptools wheel
-          python -m pip install flake8 pytest-xdist pytype pylint pylint-exit
-          python -m pip install -r requirements.txt
-          python -m pip install -r requirements-test.txt
+          pip install --upgrade pip setuptools wheel
+          pip install flake8 pytest-xdist pytype pylint pylint-exit
+          pip install -r requirements.txt
+          pip install -r requirements-test.txt
         shell: bash
       - name: Lint with flake8
         run: |
           set -xe
-          # stop the build if there are Python syntax errors or undefined names
-          cd chex
-          flake8 `find -name '*.py' | xargs` --count --select=E9,F63,F7,F82,E225,E251 --show-source --statistics
-          cd ..
+          flake8 `find chex -name '*.py' | xargs` --count --select=E9,F63,F7,F82,E225,E251 --show-source --statistics
+      - name: Lint with pylint
+        run: |
+          set -xe
+          # Fail on errors, warning, conventions and refactoring messages.
+          PYLINT_ARGS="-efail -wfail -cfail -rfail"
+
+          # Lint modules and tests separately.
+          pylint --rcfile=.pylintrc `find chex -name '*.py' | grep -v 'test.py' | xargs` || pylint-exit $PYLINT_ARGS $?
+
+          # Disable `protected-access` warnings for tests.
+          pylint --rcfile=.pylintrc `find chex -name '*_test.py' | xargs` -d W0212 || pylint-exit $PYLINT_ARGS $?
       - name: Build
         run: |
           set -xe
@@ -56,9 +64,11 @@ jobs:
           set -xe
           # Change directory to avoid importing the package from repo root.
           mkdir _testing && cd _testing
+
           # Main tests.
-          python -m pytest -n "$(grep -c ^processor /proc/cpuinfo)" --pyargs chex -k "not fake_set_n_cpu_devices_test"
+          pytest -n "$(grep -c ^processor /proc/cpuinfo)" --pyargs chex -k "not fake_set_n_cpu_devices_test"
+
           # Isolate tests that use `chex.set_n_cpu_device()`.
-          python -m pytest -n "$(grep -c ^processor /proc/cpuinfo)" --pyargs chex -k "fake_set_n_cpu_devices_test"
+          pytest -n "$(grep -c ^processor /proc/cpuinfo)" --pyargs chex -k "fake_set_n_cpu_devices_test"
           cd ..
         shell: bash
